export const headers = {headers: {'api-key': process.env.SENDINBLUE_API_KEY}};

export const SUBSCRIPTION_STATUS = {
    ABO_ACCESS: 'ABO ACCESS',
    ABO_PREMIUM: 'ABO PREMIUM',
    ABO_OFFERT: 'ABO OFFERT',
    PERDU_ACCESS: 'PERDU ACCESS',
    ABO_VITRINE: 'ABO_VITRINE',
    SUSPENDU_ACCESS: 'SUSPENDU_ACCESS',
    SUSPENDU_PREMIUM: 'SUSPENDU_PREMIUM',
    // RENOUVELE: 'RENOUVELE',
    PERDU_PREMIUM: 'PERDU PREMIUM',
    PERDU_VITRINE: 'PERDU VITRINE',
    // RENOUVELE_ABO_OFFERT: 'RENOUVELE ABO OFFERT',
    OFFERT_ARRET: 'OFFERT ARRET'
};

export const freeSubscriptionStatus = [SUBSCRIPTION_STATUS.ABO_ACCESS, SUBSCRIPTION_STATUS.ABO_OFFERT, SUBSCRIPTION_STATUS.ABO_VITRINE];
export const premiumSubscriptionStatus = [SUBSCRIPTION_STATUS.ABO_PREMIUM];
export const terminatedSubscriptionStatus = [
    SUBSCRIPTION_STATUS.PERDU_ACCESS,
    SUBSCRIPTION_STATUS.SUSPENDU_ACCESS,
    SUBSCRIPTION_STATUS.SUSPENDU_PREMIUM,
    SUBSCRIPTION_STATUS.PERDU_PREMIUM,
    SUBSCRIPTION_STATUS.PERDU_VITRINE,
    SUBSCRIPTION_STATUS.OFFERT_ARRET
];
