const {
    // Parameters
    ATTRIBUTES_ABONNEMENTS,
    ATTRIBUTES_TYPE_ABONNEMENT,
    ATTRIBUTES_CONTACTS,
    SYNCHRONISATION_PERIOD,
    // Database configuration
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_DATABASE
} = process.env;

export const attributesAbonnements = ATTRIBUTES_ABONNEMENTS ? ATTRIBUTES_ABONNEMENTS.split(',') : [];
export const attributesTypeAbonnement = ATTRIBUTES_TYPE_ABONNEMENT ? ATTRIBUTES_TYPE_ABONNEMENT.split(',') : [];
export const attributesContacts = ATTRIBUTES_CONTACTS ? ATTRIBUTES_CONTACTS.split(',') : [];
export const synchronizationPeriod = parseInt(SYNCHRONISATION_PERIOD);

export const databaseConfig = {
    host: DATABASE_HOST,
    port: DATABASE_PORT,
    user: DATABASE_USER,
    password: DATABASE_PASSWORD,
    database: DATABASE_DATABASE
};

const SUBSCRIPTION_STATUS = {
    ABO_ACCESS: 'ABO ACCESS',
    ABO_PREMIUM: 'ABO PREMIUM',
    ABO_OFFERT: 'ABO OFFERT',
    PERDU_ACCESS: 'PERDU ACCESS',
    ABO_VITRINE: 'ABO_VITRINE',
    SUSPENDU_ACCESS: 'SUSPENDU_ACCESS',
    SUSPENDU_PREMIUM: 'SUSPENDU_PREMIUM',
    // RENOUVELE: 'RENOUVELE',
    PERDU_PREMIUM: 'PERDU PREMIUM',
    PERDU_VITRINE: 'PERDU VITRINE',
    // RENOUVELE_ABO_OFFERT: 'RENOUVELE ABO OFFERT',
    OFFERT_ARRET: 'OFFERT ARRET'
};

export const freeSubscriptionStatus = [SUBSCRIPTION_STATUS.ABO_ACCESS, SUBSCRIPTION_STATUS.ABO_OFFERT, SUBSCRIPTION_STATUS.ABO_VITRINE];
export const premiumSubscriptionStatus = [SUBSCRIPTION_STATUS.ABO_PREMIUM];
export const terminatedSubscriptionStatus = [
    SUBSCRIPTION_STATUS.PERDU_ACCESS,
    SUBSCRIPTION_STATUS.SUSPENDU_ACCESS,
    SUBSCRIPTION_STATUS.SUSPENDU_PREMIUM,
    SUBSCRIPTION_STATUS.PERDU_PREMIUM,
    SUBSCRIPTION_STATUS.PERDU_VITRINE,
    SUBSCRIPTION_STATUS.OFFERT_ARRET
];
